Repository TencentBlueKing/bk-itsm, pull requests merged in 2021-12, with the labels that each got.

#216 feature: 单据评论列表新增分页
  itsm/ticket/views/ticket_remark.py
Labels: feature

#238 feature: 单据状态模块新增单元测试
  itsm/tests/components/test_utils.py
  itsm/tests/ticket_status/__init__.py
  itsm/tests/ticket_status/test_views.py
  scripts/workflows/code_quality.sh
Labels: unit test

#262 bugfix: 人员选择器增加headers，问题修复
  itsm/gateway/views.py
Labels: bug

#260 bugfix:修改权限参数传错
  frontend/pc/src/views/processManagement/apiConfigure/apiTable.vue
  frontend/pc/src/views/processManagement/publicField/index.vue
  frontend/pc/src/views/processManagement/publicTrigger/index.vue
  frontend/pc/src/views/ticket/details/index.vue
Labels: bug

#266 feature: 单据创建接口补充日志信息
  .gitignore
  itsm/auth_iam/resources/public_field.py
  itsm/openapi/ticket/views.py
Labels: feature

#270 feature: 网关接口鉴权改造
  itsm/openapi/service/views.py
  requirements.txt
Labels: feature

#273 feature: pyjwt相关依赖问题修改
  requirements.txt
Labels: bug

#275 feature: jwt 添加详细日志
  itsm/component/bkoauth/jwt_client.py
Labels: feature

#280 feature: 单据评论模块新增单元测试
  itsm/tests/ticket/test_ticket_remark.py
  itsm/tests/workflow/test_workflow_serializer.py
Labels: v2.6.1, unit test

#283 feature: iam 部分单元测试完善
  itsm/openapi/service/views.py
  itsm/tests/adapter/test_ieod.py
  itsm/tests/iam/test_iam_resource_api.py
Labels: v2.6.1, unit test

#286 feature: iam模块单元测试补充
  itsm/tests/iam/test_utils.py
Labels: v2.6.1, unit test

#287 bugfix: 工单状态查看接口取消鉴权
  itsm/project/views.py
  itsm/ticket_status/permissions.py
Labels: bug

#289 feature:补充ticket_view单元测试
  itsm/tests/ticket/test_ticket_view.py
Labels: v2.6.1, unit test

#292 feature: 修改单元测试统计规则
  itsm/tests/helper/__init__.py
  itsm/tests/helper/test_helper.py
  scripts/workflows/code_quality.sh
Labels: v2.6.1, unit test

#295 feature: 增加一部分日志打印
  itsm/ticket/tasks.py
Labels: feature, v2.6.1

#298 feature: 增加一部分日志打印
  iam/contrib/iam_migration/migrations/0010_update.py
  itsm/ticket/models/ticket.py
  support-files/iam/initial.json
Labels: feature, v2.6.1

#301 feature: 服务支持克隆
  itsm/service/managers.py
  itsm/service/views.py
  itsm/tests/service/test_service.py
Labels: feature, v2.6.1, unit test

#314 bugfix: 关联业务相关问题修复
  itsm/workflow/serializers/field.py
  itsm/workflow/views.py
Labels: bug, v2.6.1

#316 feature: 新增审批人引用变量
  itsm/component/constants/field.py
  itsm/pipeline_plugins/components/collections/itsm_sign.py
  itsm/ticket/models/ticket.py
Labels: feature, v2.6.1

#335 bugfix: 修复新的环境变量引入导致审批异常的问题
  itsm/ticket/models/ticket.py
Labels: bug, v2.6.1
