Repository TencentBlueKing/bk-itsm, pull requests merged in 2021-09, with the labels that each got.

#38 feature： merge V2.6.x develop to master
  frontend/pc/src/views/project/editProjectDialog.vue
  frontend/pc/src/views/project/index.vue
  frontend/pc/src/views/project/list.vue
  frontend/pc/src/views/service/editService/ServiceForm.vue
  frontend/pc/src/views/service/editService/ServiceSettingStep.vue
  frontend/pc/src/views/service/serviceList.vue
  frontend/pc/src/views/service/sla/index.vue
  frontend/pc/src/views/slaManager/newAddAgreement/priorityConfigur.vue
  frontend/pc/src/views/ticket/details/components/fieldsDone.vue
  frontend/pc/src/views/ticket/details/rightTicketTabs/AssociatedTab/AssociatedDialog.vue
  itsm/workflow/validators.py
Labels: feature

#42 feature: 用户组增加项目下唯一限制
  itsm/role/validators.py
Labels: feature

#43 feature: 项目关闭删除入口
  itsm/project/views.py
  itsm/sla/validators.py
Labels: feature

#45 feature: 权限中心 common actions 移除单据查看
  support-files/iam/initial_common_actions.json
Labels: feature

#50 feature: merge V2.6.x develop to master
  frontend/pc/src/components/form/selectTree/index.vue
  frontend/pc/src/i18n/lang/en.js
  frontend/pc/src/i18n/lang/zh.js
  frontend/pc/src/views/commonComponent/fieldComponent/file.vue
  frontend/pc/src/views/commonMix/field.js
  frontend/pc/src/views/project/editProjectDialog.vue
  frontend/pc/src/views/project/list.vue
  itsm/component/bkoauth/__init__.py
  itsm/component/bkoauth/jwt_client.py
  itsm/component/bkoauth/utils.py
  itsm/component/decorators.py
  itsm/component/utils/client_backend_query.py
  itsm/gateway/views.py
  itsm/openapi/service/views.py
  itsm/openapi/ticket/views.py
  itsm/project/views.py
  itsm/role/validators.py
  itsm/sla/validators.py
  itsm/ticket/migrations/0062_alter_status_processors.py
  itsm/ticket/models/ticket.py
  itsm/ticket/tasks.py
  requirements.txt
  support-files/iam/initial_common_actions.json
Labels: feature

#54 bugfix: 修复用户组编辑404的问题
  itsm/role/views.py
Labels: bug

#56 feature:版本日志更新20210909
  docs/RELEASE.md
  docs/RELEASE_EN.md
Labels: docs

#58 bugfix: 修复督办人非处理人时无法督办的问题
  itsm/ticket/permissions.py
Labels: bug

#73 Feature: 修改部分权限字段的文案
  itsm/component/constants/iam.py
Labels: feature

#87 feature: 修改权限文本
  itsm/component/constants/iam.py
Labels: feature
